### ISSUE TITLE
cannot submit block by stratum

### ISSUE THREAD

**Issue by feeleep75** [darkcoin/darkcoin#120]
Hi,

When daemon detects possible fork and you have this error message:

```
Warning: The network does not appear to fully agree! Some miners appear to be experiencing issues.
```

stratum server cannot submit block:

```
rpc error with daemon instance 0 when submitting block with submitblock {"code":-2,"message":"Safe mode: Warning: The network does not appear to fully agree! Some miners appear to be experiencing issues."}
```

**Comment by darkcoinproject** [comment]
There was a fork on the network a few days ago due to a difference of opinion between V10 and V11. The V11 caught an invalid masternode payment and refused to take it, after that there was a fork which resulted in some miners getting this error. The fork has sense been resolved and the network looks very healthy now.

**Comment by miningpoolhub** [comment]
I don't think it's solved. Experiencing v11 fork and stuck time to time.
